require('dotenv').config();
const admin = require('../src/config/firebase');

async function testNotification() {
  const token = 'ezUq0bFxQ_OKKUdwxUvW_L:APA91bHKZVWjOSt8areJlETq8x4VeFQmsPGcoxL0ZQkiL7MO1djmkvhTanUqMNoi_vvjd3SwyYkasYYe9NOSZ4l3L8eKjlt_UuPVUWje_ue0MuRnpme_tYY';
  
  const message = {
    token: token,
    notification: {
      title: 'Test Notification',
      body: 'This is a test notification from the backend.'
    },
    data: {
      test: 'true'
    }
  };

  console.log('Sending message to token:', token);
  try {
    const response = await admin.messaging().send(message);
    console.log('Successfully sent message:', response);
  } catch (error) {
    console.error('Error sending message:', error);
    if (error.code === 'messaging/mismatched-credential') {
      console.log('\n🔍 DIAGNOSIS: SenderId mismatch detected.');
      console.log('This means the FCM token was generated by an app configured with a DIFFERENT Firebase Project than this backend.');
      console.log('Backend Project ID:', JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT).project_id);
    }
  }
  process.exit(0);
}

testNotification();
